export const environmentVariables = {
  NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV,
  NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
  NEXT_PUBLIC_JSON_RPC_PROVIDER: process.env.NEXT_PUBLIC_JSON_RPC_PROVIDER,
  NEXT_PUBLIC_NFT_LOAN_FACILITATOR_CONTRACT:
    process.env.NEXT_PUBLIC_NFT_LOAN_FACILITATOR_CONTRACT,
  NEXT_PUBLIC_LEND_TICKET_CONTRACT:
    process.env.NEXT_PUBLIC_LEND_TICKET_CONTRACT,
  NEXT_PUBLIC_BORROW_TICKET_CONTRACT:
    process.env.NEXT_PUBLIC_BORROW_TICKET_CONTRACT,
  NEXT_PUBLIC_MOCK_DAI_CONTRACT: process.env.NEXT_PUBLIC_MOCK_DAI_CONTRACT,
  NEXT_PUBLIC_MOCK_PUNK_CONTRACT: process.env.NEXT_PUBLIC_MOCK_PUNK_CONTRACT,
  NEXT_PUBLIC_ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_URL,
  NEXT_PUBLIC_OPENSEA_URL: process.env.NEXT_PUBLIC_OPENSEA_URL,
  NEXT_PUBLIC_OPENSEA_API_URL: process.env.NEXT_PUBLIC_OPENSEA_API_URL,
  NEXT_PUBLIC_FACILITATOR_START_BLOCK:
    process.env.NEXT_PUBLIC_FACILITATOR_START_BLOCK,
  NEXT_PUBLIC_NFT_BACKED_LOANS_SUBGRAPH:
    process.env.NEXT_PUBLIC_NFT_BACKED_LOANS_SUBGRAPH,
  NEXT_PUBLIC_EIP721_SUBGRAPH: process.env.NEXT_PUBLIC_EIP721_SUBGRAPH,
};

for (const [k, v] of Object.entries(environmentVariables)) {
  if (!Boolean(v)) {
    throw new Error(`required environment variable ${k} undefined`);
  }
  if (v?.length === 0) {
    throw new Error(`required environment variable ${k} is empty string`);
  }
}
