import { SubgraphBuyoutEvent } from './SubgraphLoanEvents/SubgraphBuyoutEvent';
import { SubgraphCloseEvent } from './SubgraphLoanEvents/SubgraphCloseEvent';
import { SubgraphCollateralSeizureEvent } from './SubgraphLoanEvents/SubgraphCollateralSeizureEvent';
import { SubgraphCreateEvent } from './SubgraphLoanEvents/SubgraphCreateEvent';
import { SubgraphLendEvent } from './SubgraphLoanEvents/SubgraphLendEvent';
import { SubgraphRepayEvent } from './SubgraphLoanEvents/SubgraphRepayEvent';

export type SubgraphLoan = {
  id: string;
  loanAssetContractAddress: string;
  collateralContractAddress: string;
  collateralTokenId: string;
  perSecondInterestRate: string;
  accumulatedInterest: string;
  lastAccumulatedTimestamp: string;
  durationSeconds: string;
  loanAmount: string;
  closed: boolean;
  loanAssetDecimal: number;
  loanAssetSymbol: string;
  lendTicketHolder: string;
  borrowTicketHolder: string;
  endDateTimestamp: number;
  collateralTokenURI: string;
  createEvent?: SubgraphCreateEvent;
  lendEvents?: SubgraphLendEvent[];
  buyoutEvents?: SubgraphBuyoutEvent[];
  collateralSeizureEvents?: SubgraphCollateralSeizureEvent[];
  repayEvent?: SubgraphRepayEvent;
  closeEvent?: SubgraphCloseEvent;
};
