# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn run build
      - name: Spin up Postgres
        run: docker-compose up -d postgres && yarn run prisma-migrate:test
      - name: Run tests and calculate coverage
        run: yarn run test-coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-summary.json
          path: coverage/coverage-summary.json
