# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn run build
      - name: Run tests and calculate coverage
        run: |
          set -euo pipefail

          threshold=20

          # Second entry in "All files" is % of branch coverage
          coverage=`yarn run test-coverage | grep "All files" | grep -Eo '[0-9]+\.[0-9]+' | sed -n 2p`

          if (( $(echo "$coverage >= $threshold" | bc -l) )) ; then
            echo "PASS: Coverage is good."
            exit 0
          else
            echo "FAIL: Branch coverage of $coverage is insufficient to meet threshold of $threshold"
            exit 1
          fi
      - name: Comment with coverage
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-summary.json
          title: Karma Test Coverage
