# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn run build
      - name: Run tests and calculate coverage
        run: |
          set -euxo pipefail

          # Second entry in "All files" is % of branch coverage
          coverage=`yarn run test-coverage | grep "All files" | grep -Eo '[0-9]+\.[0-9]+' | sed -n 2p`

          if (( $(echo "$coverage >= 30" | bc -l) )) ; then
            exit 0
          else
            exit 1
          fi
